paths:
 /api/products/:
  get:
   summary: Obtener todos los productos
   tags:
    - Prods
   responses:
    "200":
     description: Los productos se obtuvieron de forma correcta
     content:
      application/json:
       schema:
        type: array
        items:
         $ref: "#components/schemas/Prod"
    "500":
     description: Error interno del servidor
  post:
   summary: Crear producto
   tags:
    - Prods
   requestBody:
    required: true
    content:
     application/json:
      schema:
       $ref: "#components/requestBodies/UpdateProd"
   responses:
    "200":
     description: La mascota se creo de forma correcta
     content:
      application/json:
       schema:
        type: object
        properties:
         status:
          type: string
         payload:
          $ref: "#components/schemas/Prod"
    "500":
     description: Error interno del servidor

components:
 schemas:
  Prod:
   type: object
   properties:
    _id:
     type: ObjectId
     description: id del producto
    title:
     type: string
     description: Nombre del producto
    description:
     type: string
     description: Descripcion del producto
    price:
     type: string
     description: Precio del producto
    thumbnail:
     type: string
     description: Ruta de la imagen del producto
    code:
     type: string
     description: Codigo unico del producto
    stock:
     type: number
     description: 25
   example:
    _id: ObjectId("gsa98273skjhgda8912")
    title: Teclado keyboard
    description: Keyboard Dell, ultima generacion
    price: 999
    thumbnail: "http:www.imagen/perrito.jpg"
    code: EEAS55
    stock: 47
 requestBodies:
  UpdateProd:
   type: object
   properties:
    title:
     type: string
     description: Nombre del producto
    description:
     type: string
     description: Descripcion del producto
    price:
     type: string
     description: Precio del producto
    thumbnail:
     type: string
     description: Ruta de la imagen del producto
    code:
     type: string
     description: Codigo unico del producto
    stock:
     type: number
     description: 25
   example:
    _id: ObjectId("gsa98273skjhgda8912")
    title: Teclado keyboard
    description: Keyboard Dell, ultima generacion
    price: 999
    thumbnail: "http:www.imagen/perrito.jpg"
    code: EEAS55
    stock: 47
    